### ISSUE TITLE
Improved support for sparse data matrices

### ISSUE THREAD

**Issue by rileyjmurray** [BallisticLA/RandBLAS#77]
PR #76 added initial (undocumented) support for sparse data matrices. Right now we only use that functionality to handle applying sparse sketching operators to dense data matrices. I'm opening this issue to document next steps that are needed before we make sparse data matrices part of the public API.

* Namespace changes: #81
    * [x] Move some sparse matrix datatypes into top-level ``RandBLAS::``.
    * [x] Remove the ``RandBLAS_Testing`` namespace (currently only used in ``RandBLAS/test_util.hh``; move code in that namespace to other, more appropriate files in ``test/..``.
* Templating changes: #80
    * [x] Replace int64_t in sparse matrices with ordinal type that can only be a signed integer. This is needed for zero-copy views of sparse matrices that use 32-bit integers in one (or more) of their index vectors.
* Testing
    * [x] Create testing infrastructure for multiplying a dense matrix (represented by a plain buffer) and an abstract linear operator. 
         * PR #80.
    * [x] Port tests for dense and sparse sketching of dense matrices into the new framework.
         * PR #80.
    * [x] Write dedicated tests for sparse-times-dense matmul that don't rely on the tests for sparse sketching operators times dense matrices.
         * PR #81.
* Functionality expansions
     * Definite
          * [x] ~Allow one-based indexing in multiply function(s).~ After attending the second sparse BLAS workshop it's become clear that this isn't essential. I just need to raise errors in functions that require 0-based indexing and I need functions to convert between 1-indexing and 0-indexing in-place. Completed in #83.
          * [x] Native support for multiplication with CSC and CSR. (PR #82)
          * [x] View transposed CSR as CSC. (PR #82)
          * [x] View transposed CSC as CSR. (PR #82)
     * Possible
          * [x] LSPGEMM - CSC, CSR, COO (PR #82)
          * [x] RSPGEMM - CSC, CSR, COO (PR #82)
